# Generated by Django 4.1 on 2024-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonial",
            old_name="quote",
            new_name="feedback",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="category",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="details_link",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(upload_to="portfolio/images/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(upload_to="testimonials/images/"),
        ),
    ]
