# Generated by Django 4.1 on 2024-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0005_alter_portfolio_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                choices=[
                    ("app", "App"),
                    ("product", "Product"),
                    ("branding", "Branding"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio/"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
