# Generated by Django 4.1 on 2024-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/images/%Y/%m/%d/"
            ),
        ),
    ]
