# Generated by Django 4.1 on 2024-11-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_hook_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="blog/images/%Y/%m/%d/"
            ),
        ),
    ]
