# Generated by Django 4.1 on 2024-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("app", "App"),
                            ("product", "Product"),
                            ("branding", "Branding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("details_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quote", models.TextField()),
                ("image", models.ImageField(upload_to="testimonials/")),
            ],
        ),
    ]
