# Generated by Django 4.1 on 2024-12-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0011_remove_teammember_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="bio",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="position",
            new_name="hook_text",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="last_name",
            new_name="title",
        ),
    ]
