# Generated by Django 4.1 on 2024-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0002_rename_quote_testimonial_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(upload_to="portfolio/"),
        ),
    ]
