# Generated by Django 4.1 on 2024-12-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0009_portfolio_project_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="team_images/")),
                ("learn_more_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
