# Generated by Django 4.1 on 2024-12-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0010_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="learn_more_link",
        ),
    ]
