# Generated by Django 4.1 on 2024-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0013_raspberry_warning_remove_portfolio_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raspberry",
            name="category",
            field=models.CharField(
                choices=[
                    ("sensor", "Sensor"),
                    ("input", "Input"),
                    ("control", "Control"),
                    ("output", "Output"),
                    ("etc", "etc"),
                ],
                max_length=50,
            ),
        ),
    ]
