# Generated by Django 4.1 on 2024-12-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0015_ara"),
    ]

    operations = [
        migrations.AddField(
            model_name="ara",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="raspberry",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
