# Generated by Django 5.1.2 on 2024-12-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0016_ara_hook_text_raspberry_hook_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="raspberry",
            name="blog_url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="블로그 URL"
            ),
        ),
    ]
