# Generated by Django 5.1.2 on 2024-12-02 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "categories"},
        ),
    ]
