# Generated by Django 4.1 on 2024-11-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_hook_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
