# Generated by Django 5.1.2 on 2024-12-02 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
    ]
